version: '3'

services:
  web:
    image: olegsmetanin/dockercloud-hello-world
    environment:
      - VIRTUAL_HOST=cloud.example.com
      - VIRTUAL_NETWORK=webproxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.example.com
      - LETSENCRYPT_EMAIL=me@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default:
    external:
      name: webproxy
